version: "3"
services:

  jenkins:
    image: myjenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    volumes:
      - ./downloads:/var/jenkins_home/downloads
      - ./jobs:/var/jenkins_home/jobs
      - ./m2deps:/var/jenkins_home/.m2/repository
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  frontend:
