version: "3"
services:

  jenkins:
    image: myjenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    env_file:
      - ./docker-inputs.env
      - /tmp/docker-inputs.env
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  
#  artifactory:
#    image: docker.bintray.io/jfrog/artifactory-oss:5.8.4
#    container_name: artifactory
#    ports:
#     - 8081:8081
#    networks:
#      - frontend
#    volumes:
#     - /data/artifactory:/var/opt/jfrog/artifactory
##    Add extra Java options by uncommenting the following lines
##    environment:
##     - EXTRA_JAVA_OPTIONS=-Xmx4g
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 40000
networks:
  frontend:
