version: "3"
services:

  jenkins:
    image: myjenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    env_file:
      - ./docker-inputs.env
      - /tmp/docker-inputs.env
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
 
networks:
  frontend:
